// Command sqlite runs gohan end to end against an in-memory SQLite
// database (modernc.org/sqlite, no cgo): create a table, insert, upsert,
// select, update and delete, printing each statement and its result.
package main

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"

	"github.com/oddbit-project/gohan"
	_ "modernc.org/sqlite"
)

// User maps the users table. The id is generated by the database, so it is
// tagged auto and left out of INSERTs and UPDATEs.
type User struct {
	ID     int64  `db:"id" auto:"true"`
	Name   string `db:"name"`
	Email  string `db:"email"`
	Visits int64  `db:"visits"`
}

func main() {
	ctx := context.Background()

	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	// Every connection to ":memory:" is a separate database: keep one.
	db.SetMaxOpenConns(1)

	// The dialect can be looked up by database/sql driver name.
	d, err := gohan.DialectFor("sqlite")
	if err != nil {
		log.Fatal(err)
	}

	// DDL is not gohan's job: write it by hand.
	if _, err := db.ExecContext(ctx, `CREATE TABLE users (
		id     INTEGER PRIMARY KEY,
		name   TEXT    NOT NULL,
		email  TEXT    NOT NULL UNIQUE,
		visits INTEGER NOT NULL DEFAULT 0
	)`); err != nil {
		log.Fatal(err)
	}

	// INSERT from structs.
	exec(ctx, db, d, "insert", gohan.Insert("users").Rows(
		User{Name: "alice", Email: "alice@example.com", Visits: 1},
		User{Name: "bob", Email: "bob@example.com", Visits: 1},
	))

	// Upsert: a second visit by alice bumps her counter and takes the new
	// name instead of failing on the UNIQUE email.
	exec(ctx, db, d, "upsert", gohan.Insert("users").
		Columns("name", "email", "visits").
		Values("Alice", "alice@example.com", 1).
		OnConflict("email").
		DoUpdate(map[string]any{
			"name":   gohan.Excluded("name"),
			"visits": gohan.Raw("? + 1", gohan.Col("users.visits")),
		}))

	// INSERT ... RETURNING the generated id.
	var carolID int64
	query, args := build(d, "insert returning", gohan.Insert("users").
		Columns("name", "email").
		Values("carol", "carol@example.com").
		Returning("id"))
	if err := db.QueryRowContext(ctx, query, args...).Scan(&carolID); err != nil {
		log.Fatal(err)
	}
	fmt.Println("  -> carol has id", carolID)

	list(ctx, db, d)

	// UPDATE from a struct, limited to the fields that changed.
	exec(ctx, db, d, "update", gohan.Update("users").
		SetRecord(User{Email: "carol@example.org"}, gohan.IncludeFields("email")).
		Where(gohan.Col("id").Eq(carolID)))

	// DELETE with a WHERE clause.
	exec(ctx, db, d, "delete", gohan.Delete("users").
		Where(gohan.Col("visits").Lt(2), gohan.Col("email").HasSuffix("@example.com")))

	// A DELETE without WHERE is refused before it reaches the database.
	if _, _, err := gohan.Delete("users").Build(d); errors.Is(err, gohan.ErrNoWhere) {
		fmt.Println("\nunfiltered delete refused:", err)
	}

	list(ctx, db, d)
}

// build renders stmt under d and prints it.
func build(d gohan.Dialect, label string, stmt gohan.Statement) (string, []any) {
	query, args, err := stmt.Build(d)
	if err != nil {
		log.Fatalf("%s: %v", label, err)
	}
	fmt.Printf("\n%s:\n  %s\n  args: %v\n", label, query, args)
	return query, args
}

// exec builds and runs a statement that returns no rows.
func exec(ctx context.Context, db *sql.DB, d gohan.Dialect, label string, stmt gohan.Statement) {
	query, args := build(d, label, stmt)
	res, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		log.Fatalf("%s: %v", label, err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("  -> rows affected:", n)
}

// list selects every user, ordered by id, and prints them.
func list(ctx context.Context, db *sql.DB, d gohan.Dialect) {
	query, args := build(d, "select", gohan.Select("id", "name", "email", "visits").
		From("users").
		OrderBy("id"))
	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Email, &u.Visits); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("  -> %+v\n", u)
	}
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
}
